name: Build

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Build
      run: |
       chmod +x gradlew
       ./gradlew assembleDebug
    - name: Store generated universal APK file
      uses: actions/upload-artifact@v2
      with:
        name: Kayuri-universal
        path: |
            ./app/build/outputs/apk/debug/Kayuri-*-universal-debug.apk
    - name: Store generated arm64-v8a APK file
      uses: actions/upload-artifact@v2
      with:
        name: Kayuri-arm64-v8a
        path: |
          ./app/build/outputs/apk/debug/Kayuri-*-v8a-debug.apk
    - name: Store generated armeabi-v7a APK file
      uses: actions/upload-artifact@v2
      with:
        name: kayuri-armeabi-v7a
        path: |
          ./app/build/outputs/apk/debug/Kayuri-*-armeabi-v7a-debug.apk
    - name: Store generated x86_64 APK file
      uses: actions/upload-artifact@v2
      with:
        name: Kayuri-x86_64
        path: |
          ./app/build/outputs/apk/debug/Kayuri-*-x86_64-debug.apk
    - name: Store generated x86 APK file
      uses: actions/upload-artifact@v2
      with:
        name: kayuri-x86
        path: |
          ./app/build/outputs/apk/debug/Kayuri-*-x86-debug.apk
